### ISSUE TITLE
Stan zrealizowanych elementów programu ciągle się ładuje, i się nigdy nie załaduje

### ISSUE THREAD

**Issue by YellowDuckyDuck** [panmrherobrine/VersionCompiler#1]

**Comment by panmrherobrine** [comment]
Taki jest zamysł tego paska. On pokazuje tylko stan wykonania całej części programu Przy 100% zostanie on usunięty i program będzie otwarty na propozycje.

**Comment by YellowDuckyDuck** [comment]
Acha dzięki
